---
title: "INFO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Datensatz-Quellen:
- Netflix
  https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv
- Bechdel
  https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv
- Equality Index
  https://www.cfr.org/legal-barriers/country-rankings/


Titel-Zeile:
  - Land (groß)
  - Score, Anzahl Filme, Durchgefallene Filme

Kapitel:
  - Equality Score
  - Bechdel-Test
  - Allgemeine Equality-Situation
  - Vergleich/Zusammenfassung/Fazit


Diagramm-Ideen:
  - Balkendiagramme (spezifisch: Diagramm zum Gleichstellungsindex je Land) animieren, sodass sich die Balken erst beim Öffnen der Seite aufbaut
  - Palette:  scale_color_continuous_sequential(Palette = "Purple-Orange")
  - Punktdiagramm: Gründe für das Durchfallen (Jana Bechdel)
  - Boxplot/Liniendiagramm/Punktdiagramm: Budget
  - Anzahl Fails/Pass Liniendiagramm (Haris Bechdel)
  - Bechdeltest: Cleantest (großer Datensatz, nicht der von 0-3 geht) 
  - Genres nach Fail und Pass vergleichen (MK Bechdel)
  - Facet Wrap Density Plot (Genre + Gross) (Bechdel VM) -> sehr schön
